### ISSUE TITLE
Add official function? (Zeus & Arsenal)

### ISSUE THREAD

**Issue by GodofMonkeys** [ole1986/a3-adminhelper#31]
Hi, I love this admin mod, but are you plan to add official function (Zeus & Arsenal) into this mod?
If can this will be nice.

Thanks

**Comment by ole1986** [comment]
@GodofMonkeys I can try to spend some time on it,,, 

Just let me know what are the important functions you need.
Otherwise you can build you own extension at any time..
Related links building extensions: 
* https://github.com/ole1986/a3-admintoolkit#extensions
* https://github.com/ole1986/a3-admintoolkit/blob/master/%40MissionFile/README.md

**Comment by GodofMonkeys** [comment]
Thanks.
The Zeus can edit scene more quick and easy. And Arsenal too.

**Comment by ole1986** [comment]
@GodofMonkeys can you give me some examples?
