### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by vaillki** [ole1986/a3-adminhelper#41]
Hello, 

I tried to install the admintoolkit on the Arma 3 life server andi it's doesn't work... I've got as an error to say "Admintoolkit Login Failed - Check your server config.cpp". Can you help me please ?

Excuse me for my english, I'm a french guy !

**Comment by ole1986** [comment]
Make sure you have repacked the admintoolkit_servercfg.pbo once you filled up the config with your player uid

**Comment by vaillki** [comment]
Yes of course, I put my player uid into the admin list

**Comment by ole1986** [comment]
Login failed means login failed... So double check the your player uid, and the format you are writing it into the config.cpp and make sure you have re-uploaded the admintool_servercfg.pbo onto your server

**Comment by ole1986** [comment]
Problem solved?

**Comment by vaillki** [comment]
Yes for this problem but your admin menu doesn't work. I would like to spawn vehicle and nothings happend... Your admintoolkit is just for Exile ?

**Comment by ole1986** [comment]
actually its not, it will also work without exile...
Have you patched your mission file using the `./setup.ps1 -PatchMission` cmdlet ?

**Comment by ole1986** [comment]
If you still having issues, please pastebin the RPT from client and server.

**Comment by Batseyy** [comment]
Hi, I'm not sure if anyone will see this but I've been having the same issue as the guy above. All the UI works and seems great but when I try to do anything I get "Admin Toolkit LOG IN FAILED - check server config files" you said above that it's due to the Steam ID needing entered but I have it in, it's packed as a PBO and all typed correctly. Could it be something to do with the fact it have a custom URL and not a steam ID as such? Any help is very appreciated! Thanks
